# Generated by Django 4.2.5 on 2023-09-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='categroies',
            field=models.ManyToManyField(related_name='products', to='product_api.category'),
        ),
    ]
