# Generated by Django 4.2.5 on 2023-09-13 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0002_remove_category_products_product_categroies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categroies',
            new_name='categories',
        ),
    ]
