# Generated by Django 4.2.5 on 2023-11-03 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0005_remove_product_image_url_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_url',
            new_name='url',
        ),
    ]
